
-- Seed entities
INSERT INTO public.knowledge_entities (name, entity_type, description, civilization, impact_score) VALUES
('Quantum Error Correction', 'technology', 'Techniques for protecting quantum information from decoherence', 'Quantum', 0.92),
('Topological Qubits', 'technology', 'Fault-tolerant qubits using topological properties of matter', 'Quantum', 0.88),
('Quantum Key Distribution', 'technology', 'Secure communication using quantum mechanics principles', 'Quantum', 0.85),
('Quantum Supremacy', 'concept', 'Demonstration of quantum advantage over classical computers', 'Quantum', 0.95),
('Post-Quantum Cryptography', 'technology', 'Cryptographic algorithms resistant to quantum attacks', 'Quantum', 0.87),
('Quantum Entanglement Networks', 'technology', 'Distributed quantum computing via entangled particles', 'Quantum', 0.83),
('CERN Quantum Lab', 'organization', 'Leading quantum research facility in Europe', 'Quantum', 0.78),
('Quantum Annealing', 'technology', 'Optimization technique using quantum fluctuations', 'Quantum', 0.76),
('Shor Algorithm Advances', 'event', 'Breakthroughs in integer factorization on quantum hardware', 'Quantum', 0.80),
('Quantum Memory', 'technology', 'Long-lived quantum state storage for network nodes', 'Quantum', 0.74),
('Quantum Sensing', 'technology', 'Ultra-precise measurements using quantum coherence', 'Quantum', 0.72),
('Quantum Internet Protocol', 'concept', 'Standards for quantum network communication', 'Quantum', 0.79),
('Helium-3 Cooling', 'resource', 'Cryogenic resource for quantum processor operation', 'Quantum', 0.60),
('Dr. Quantum (Agent)', 'researcher', 'Lead quantum research agent in MEEET STATE', 'Quantum', 0.70),
('Quantum Teleportation', 'concept', 'Transfer of quantum states across distances', 'Quantum', 0.82),
('Quantum Simulation', 'technology', 'Simulating quantum systems for material science', 'Quantum', 0.77),
('Transformer Architecture', 'technology', 'Self-attention based neural network architecture', 'AI', 0.96),
('Reinforcement Learning', 'concept', 'Learning through trial and reward signals', 'AI', 0.90),
('Neural Architecture Search', 'technology', 'Automated design of neural network architectures', 'AI', 0.84),
('Federated Learning', 'technology', 'Distributed ML training without sharing raw data', 'AI', 0.86),
('AI Alignment', 'concept', 'Ensuring AI systems act according to human values', 'AI', 0.93),
('Large Language Models', 'technology', 'Massive pretrained models for language understanding', 'AI', 0.97),
('OpenAI Research', 'organization', 'Leading AI research lab focused on AGI safety', 'AI', 0.91),
('DeepMind', 'organization', 'Google subsidiary advancing AI capabilities', 'AI', 0.89),
('Mixture of Experts', 'technology', 'Sparse activation for efficient large models', 'AI', 0.82),
('AI Ethics Board', 'organization', 'Governance body for AI deployment standards', 'AI', 0.75),
('Multimodal AI', 'concept', 'AI systems processing multiple data modalities', 'AI', 0.88),
('Autonomous Agents', 'concept', 'Self-directed AI systems making independent decisions', 'AI', 0.87),
('GPU Compute Clusters', 'resource', 'Hardware infrastructure for AI training', 'AI', 0.70),
('Knowledge Distillation', 'technology', 'Transferring knowledge from large to small models', 'AI', 0.78),
('Emergent Behavior', 'concept', 'Unexpected capabilities arising from model scale', 'AI', 0.85),
('AI Governance Summit 2026', 'event', 'Global summit on AI regulation and governance', 'AI', 0.73),
('Fusion Reactor Design', 'technology', 'Next-generation tokamak and stellarator designs', 'Energy', 0.94),
('Solid-State Batteries', 'technology', 'High-density energy storage without liquid electrolyte', 'Energy', 0.91),
('Solar Perovskites', 'technology', 'Next-gen solar cells with higher efficiency', 'Energy', 0.87),
('Green Hydrogen', 'technology', 'Hydrogen produced from renewable energy sources', 'Energy', 0.85),
('Smart Grid AI', 'technology', 'AI-optimized power grid management', 'Energy', 0.83),
('ITER Project', 'organization', 'International thermonuclear experimental reactor', 'Energy', 0.90),
('Carbon Capture', 'technology', 'Technologies for removing CO2 from atmosphere', 'Energy', 0.82),
('Nuclear Microreactors', 'technology', 'Small modular nuclear reactors for remote deployment', 'Energy', 0.79),
('Superconducting Cables', 'technology', 'Zero-resistance power transmission lines', 'Energy', 0.76),
('Lithium Reserves', 'resource', 'Global lithium supply for battery production', 'Energy', 0.68),
('Energy Harvesting', 'concept', 'Capturing ambient energy from environment', 'Energy', 0.74),
('Thorium Fuel Cycle', 'concept', 'Alternative nuclear fuel with less waste', 'Energy', 0.77),
('Grid-Scale Storage', 'technology', 'Large battery systems for grid stabilization', 'Energy', 0.80),
('Wireless Power Transfer', 'technology', 'Transmitting electrical energy without wires', 'Energy', 0.71),
('COP31 Climate Summit', 'event', 'Global climate negotiations on energy transition', 'Energy', 0.72),
('Plasma Confinement', 'concept', 'Containing superheated plasma for fusion reactions', 'Energy', 0.86),
('CRISPR-Cas13', 'technology', 'RNA-targeting gene editing tool', 'Biotech', 0.93),
('Synthetic Biology', 'concept', 'Engineering biological systems for new functions', 'Biotech', 0.91),
('mRNA Therapeutics', 'technology', 'Messenger RNA-based treatments beyond vaccines', 'Biotech', 0.89),
('Organ-on-Chip', 'technology', 'Microfluidic devices simulating organ function', 'Biotech', 0.84),
('Longevity Research', 'concept', 'Scientific pursuit of extended human lifespan', 'Biotech', 0.88),
('Brain-Computer Interface', 'technology', 'Direct neural connections to digital systems', 'Biotech', 0.90),
('Moderna Labs', 'organization', 'Leading mRNA therapeutic development', 'Biotech', 0.82),
('Microbiome Engineering', 'technology', 'Designing gut microbiota for health outcomes', 'Biotech', 0.79),
('Xenotransplantation', 'concept', 'Cross-species organ transplantation', 'Biotech', 0.76),
('Protein Folding AI', 'technology', 'AI prediction of 3D protein structures', 'Biotech', 0.92),
('Bioprinting', 'technology', '3D printing of living tissue and organs', 'Biotech', 0.85),
('Gene Therapy Vectors', 'resource', 'Viral vectors for delivering gene therapies', 'Biotech', 0.73),
('Epigenetic Reprogramming', 'concept', 'Reversing cellular aging through epigenetic changes', 'Biotech', 0.87),
('WHO Pandemic Preparedness', 'event', 'Global health coordination for future pandemics', 'Biotech', 0.70),
('Digital Twins (Medical)', 'technology', 'Virtual replicas of patients for treatment simulation', 'Biotech', 0.81),
('Neuromorphic Biosensors', 'technology', 'Brain-inspired sensors for biological monitoring', 'Biotech', 0.78),
('Mars Colony Architecture', 'concept', 'Designs for sustainable human habitats on Mars', 'Space', 0.91),
('Ion Propulsion', 'technology', 'Electric spacecraft propulsion for deep space', 'Space', 0.85),
('Space Debris Removal', 'technology', 'Active systems for cleaning orbital debris', 'Space', 0.82),
('Lunar Mining', 'concept', 'Extraction of resources from the Moon surface', 'Space', 0.80),
('SpaceX Starship', 'technology', 'Fully reusable heavy-lift launch vehicle', 'Space', 0.93),
('James Webb Telescope', 'technology', 'Deep space infrared observatory', 'Space', 0.88),
('ESA Artemis Program', 'organization', 'European Space Agency lunar exploration', 'Space', 0.79),
('Asteroid Mining Corp', 'organization', 'Commercial asteroid resource extraction', 'Space', 0.76),
('Space Solar Power', 'concept', 'Orbital solar collectors beaming energy to Earth', 'Space', 0.84),
('Radiation Shielding', 'technology', 'Protection against cosmic radiation for crews', 'Space', 0.77),
('Orbital Manufacturing', 'concept', 'Zero-gravity industrial production', 'Space', 0.75),
('Helium-3 Lunar Deposits', 'resource', 'Fusion fuel reserves on the Moon', 'Space', 0.83),
('Interstellar Probe', 'concept', 'Spacecraft designed for travel beyond solar system', 'Space', 0.70),
('Space Habitat Rotation', 'technology', 'Artificial gravity via centrifugal force', 'Space', 0.73),
('Lagrange Point Stations', 'concept', 'Space stations at gravitationally stable points', 'Space', 0.72),
('Mars Sample Return', 'event', 'Mission to bring Martian soil samples to Earth', 'Space', 0.86)
ON CONFLICT (name, entity_type) DO NOTHING;

-- Seed relationships
INSERT INTO public.knowledge_relationships (source_entity_id, target_entity_id, relationship_type, strength, description)
SELECT s.id, t.id, r.rel_type, r.str, r.d
FROM (VALUES
  ('Quantum Error Correction', 'technology', 'Topological Qubits', 'technology', 'enables', 0.9, 'Error correction enables practical topological qubits'),
  ('Quantum Supremacy', 'concept', 'Shor Algorithm Advances', 'event', 'depends_on', 0.85, 'Supremacy via algorithmic advances'),
  ('Quantum Key Distribution', 'technology', 'Post-Quantum Cryptography', 'technology', 'conflicts_with', 0.7, 'Competing quantum-safe approaches'),
  ('Quantum Entanglement Networks', 'technology', 'Quantum Internet Protocol', 'concept', 'depends_on', 0.88, 'Networks require protocols'),
  ('Quantum Memory', 'technology', 'Quantum Entanglement Networks', 'technology', 'enables', 0.82, 'Memory enables networks'),
  ('Transformer Architecture', 'technology', 'Large Language Models', 'technology', 'enables', 0.98, 'Transformers are foundation of LLMs'),
  ('Reinforcement Learning', 'concept', 'Autonomous Agents', 'concept', 'enables', 0.91, 'RL enables agent decision-making'),
  ('AI Alignment', 'concept', 'Autonomous Agents', 'concept', 'synergizes_with', 0.87, 'Alignment ensures safe autonomy'),
  ('Large Language Models', 'technology', 'Emergent Behavior', 'concept', 'enables', 0.84, 'Scale leads to emergence'),
  ('Mixture of Experts', 'technology', 'Large Language Models', 'technology', 'synergizes_with', 0.80, 'MoE makes LLMs efficient'),
  ('Federated Learning', 'technology', 'AI Ethics Board', 'organization', 'synergizes_with', 0.72, 'Privacy aligns with ethics'),
  ('Fusion Reactor Design', 'technology', 'Plasma Confinement', 'concept', 'depends_on', 0.95, 'Fusion requires confinement'),
  ('Solid-State Batteries', 'technology', 'Grid-Scale Storage', 'technology', 'evolves_into', 0.85, 'Solid-state enables grid storage'),
  ('Solar Perovskites', 'technology', 'Green Hydrogen', 'technology', 'enables', 0.78, 'Cheap solar enables hydrogen'),
  ('Smart Grid AI', 'technology', 'Grid-Scale Storage', 'technology', 'synergizes_with', 0.82, 'AI optimizes storage'),
  ('CRISPR-Cas13', 'technology', 'mRNA Therapeutics', 'technology', 'synergizes_with', 0.86, 'RNA editing complements mRNA'),
  ('Protein Folding AI', 'technology', 'Synthetic Biology', 'concept', 'enables', 0.90, 'Structure prediction accelerates bioengineering'),
  ('Brain-Computer Interface', 'technology', 'Neuromorphic Biosensors', 'technology', 'depends_on', 0.83, 'BCIs require biosensors'),
  ('Longevity Research', 'concept', 'Epigenetic Reprogramming', 'concept', 'depends_on', 0.88, 'Longevity requires epigenetics'),
  ('Bioprinting', 'technology', 'Organ-on-Chip', 'technology', 'evolves_into', 0.79, 'Bioprinting extends organ chips'),
  ('Mars Colony Architecture', 'concept', 'SpaceX Starship', 'technology', 'depends_on', 0.92, 'Colonies require transport'),
  ('Lunar Mining', 'concept', 'Helium-3 Lunar Deposits', 'resource', 'depends_on', 0.88, 'Mining targets He-3'),
  ('Space Debris Removal', 'technology', 'Ion Propulsion', 'technology', 'depends_on', 0.75, 'Debris removal uses thrusters'),
  ('Space Solar Power', 'concept', 'Orbital Manufacturing', 'concept', 'synergizes_with', 0.80, 'Manufacturing enables assembly'),
  ('Quantum Simulation', 'technology', 'Protein Folding AI', 'technology', 'synergizes_with', 0.88, 'Quantum accelerates protein prediction'),
  ('Quantum Sensing', 'technology', 'Brain-Computer Interface', 'technology', 'enables', 0.76, 'Quantum sensors improve neural detection'),
  ('Large Language Models', 'technology', 'Synthetic Biology', 'concept', 'enables', 0.81, 'LLMs design biological sequences'),
  ('Federated Learning', 'technology', 'Digital Twins (Medical)', 'technology', 'enables', 0.77, 'Privacy learning for patient twins'),
  ('Smart Grid AI', 'technology', 'Fusion Reactor Design', 'technology', 'synergizes_with', 0.79, 'AI manages fusion distribution'),
  ('Helium-3 Lunar Deposits', 'resource', 'Fusion Reactor Design', 'technology', 'enables', 0.90, 'Lunar He-3 fuels fusion'),
  ('Space Solar Power', 'concept', 'Green Hydrogen', 'technology', 'enables', 0.74, 'Orbital solar powers hydrogen'),
  ('Quantum Annealing', 'technology', 'Neural Architecture Search', 'technology', 'synergizes_with', 0.72, 'Quantum optimization improves NAS'),
  ('Radiation Shielding', 'technology', 'mRNA Therapeutics', 'technology', 'synergizes_with', 0.68, 'mRNA repairs radiation damage'),
  ('James Webb Telescope', 'technology', 'Mars Sample Return', 'event', 'synergizes_with', 0.65, 'Webb guides sample return'),
  ('Nuclear Microreactors', 'technology', 'Mars Colony Architecture', 'concept', 'enables', 0.84, 'Microreactors power Mars'),
  ('Superconducting Cables', 'technology', 'Quantum Entanglement Networks', 'technology', 'enables', 0.78, 'Superconductors enable interconnects'),
  ('Multimodal AI', 'concept', 'Organ-on-Chip', 'technology', 'synergizes_with', 0.73, 'AI analyzes organ chip data'),
  ('Knowledge Distillation', 'technology', 'Microbiome Engineering', 'technology', 'enables', 0.69, 'Compact AI for microbiome'),
  ('Quantum Teleportation', 'concept', 'Quantum Internet Protocol', 'concept', 'part_of', 0.92, 'Teleportation is core quantum primitive')
) AS r(sn, st, tn, tt, rel_type, str, d)
JOIN public.knowledge_entities s ON s.name = r.sn AND s.entity_type = r.st
JOIN public.knowledge_entities t ON t.name = r.tn AND t.entity_type = r.tt
ON CONFLICT (source_entity_id, target_entity_id, relationship_type) DO NOTHING;
